"""
# AUTOGENERATED FILE - DO NOT EDIT MANUALLY
# Generated by DagGenerator on 2025-09-29T14:28:38.077622
# For environment: DEV
"""
from pendulum import datetime
from datetime import timedelta
from airflow.models import DagRun as DagRunModel
from airflow.models.dag import DAG
from airflow.models.dagrun import DagRun
from airflow.utils.task_group import TaskGroup

# Import your custom operator
from plugins.operators.warehouse_etl_operator import WarehouseEtlOperator


with DAG(
    dag_id="workflow-warehouse__incremental_upsert__dev",
    start_date=datetime(2025, 1, 1),
    schedule="0 2 * * *",
    catchup=False,
    is_paused_upon_creation=True,
    tags=["warehouse", "autogenerated", "incremental_upsert", "dev"],
    doc_md="""Daily incremental_upsert at 2AM"""
) as dag:
    # Read the hotfix flag from the DAG run config at runtime
    dag_runs = DagRunModel.find(dag_id=dag.dag_id)
    dag_run: DagRun = dag_runs[-1] if dag_runs else None
    hotfix_flag = dag_run.conf.get("hotfix", False) if dag_run and dag_run.conf else False


    with TaskGroup(group_id="Batch_1_Stage_1") as tg_1:
                    d_student__nossasenhoradagloria_tag_ong_br = WarehouseEtlOperator(
                    task_id="d_student__nossasenhoradagloria_tag_ong_br",
                    table_execution_dict={'table_name': 'd_student', 'stage': 1, 'database': 'nossasenhoradagloria.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/d_student.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/d_student.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 5000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'nossasenhoradagloria.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student dimension table with personal information', 'created_at': '2025-09-29T14:28:38.077520', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_2_Stage_1") as tg_2:
                    d_student__buzios_tag_ong_br = WarehouseEtlOperator(
                    task_id="d_student__buzios_tag_ong_br",
                    table_execution_dict={'table_name': 'd_student', 'stage': 1, 'database': 'buzios.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/d_student.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/d_student.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 5000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'buzios.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student dimension table with personal information', 'created_at': '2025-09-29T14:28:38.077530', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_3_Stage_1") as tg_3:
                    d_student__boquim_tag_ong_br = WarehouseEtlOperator(
                    task_id="d_student__boquim_tag_ong_br",
                    table_execution_dict={'table_name': 'd_student', 'stage': 1, 'database': 'boquim.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/d_student.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/d_student.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 5000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'boquim.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student dimension table with personal information', 'created_at': '2025-09-29T14:28:38.077536', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_4_Stage_1") as tg_4:
                    d_student_discipline__nossasenhoradagloria_tag_ong_br = WarehouseEtlOperator(
                    task_id="d_student_discipline__nossasenhoradagloria_tag_ong_br",
                    table_execution_dict={'table_name': 'd_student_discipline', 'stage': 1, 'database': 'nossasenhoradagloria.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/d_student_discipline.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/d_student_discipline.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 10000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'nossasenhoradagloria.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student discipline results dimension table', 'created_at': '2025-09-29T14:28:38.077541', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_5_Stage_1") as tg_5:
                    d_student_discipline__buzios_tag_ong_br = WarehouseEtlOperator(
                    task_id="d_student_discipline__buzios_tag_ong_br",
                    table_execution_dict={'table_name': 'd_student_discipline', 'stage': 1, 'database': 'buzios.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/d_student_discipline.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/d_student_discipline.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 10000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'buzios.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student discipline results dimension table', 'created_at': '2025-09-29T14:28:38.077545', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_6_Stage_1") as tg_6:
                    d_student_discipline__boquim_tag_ong_br = WarehouseEtlOperator(
                    task_id="d_student_discipline__boquim_tag_ong_br",
                    table_execution_dict={'table_name': 'd_student_discipline', 'stage': 1, 'database': 'boquim.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/d_student_discipline.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/d_student_discipline.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 10000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'boquim.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student discipline results dimension table', 'created_at': '2025-09-29T14:28:38.077548', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_7_Stage_2") as tg_7:
                    f_avaliation__nossasenhoradagloria_tag_ong_br = WarehouseEtlOperator(
                    task_id="f_avaliation__nossasenhoradagloria_tag_ong_br",
                    table_execution_dict={'table_name': 'f_avaliation', 'stage': 2, 'database': 'nossasenhoradagloria.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/f_avaliation.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/f_avaliation.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 15000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'nossasenhoradagloria.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student evaluation fact table', 'created_at': '2025-09-29T14:28:38.077565', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_8_Stage_2") as tg_8:
                    f_avaliation__buzios_tag_ong_br = WarehouseEtlOperator(
                    task_id="f_avaliation__buzios_tag_ong_br",
                    table_execution_dict={'table_name': 'f_avaliation', 'stage': 2, 'database': 'buzios.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/f_avaliation.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/f_avaliation.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 15000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'buzios.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student evaluation fact table', 'created_at': '2025-09-29T14:28:38.077570', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    with TaskGroup(group_id="Batch_9_Stage_2") as tg_9:
                    f_avaliation__boquim_tag_ong_br = WarehouseEtlOperator(
                    task_id="f_avaliation__boquim_tag_ong_br",
                    table_execution_dict={'table_name': 'f_avaliation', 'stage': 2, 'database': 'boquim.tag.ong.br', 'source_name': '{SOURCE_NAME}', 'target_schema': '{TARGET_SCHEMA}', 'trigger': 'incremental_upsert', 'model': 'tables/f_avaliation.yml', 'sql_path': '/Users/paulomac/Documents/ipti-airflow-migration/br.tag.data.pipeline/airflow_migration/config/warehouse_etl/tables/f_avaliation.sql', 'incremental_config': {'source_timestamp_columns': ['updated_at'], 'target_timestamp_column': 'inserted_at', 'lookback_hours': 24, 'batch_size': 15000, 'full_refresh': False}, 'upsert_config': {'source_key_columns': ['HASH_ID'], 'target_key_columns': ['HASH_ID']}, 'pool': 'mysql_prod_pool', 'retries': 1, 'retry_delay_minutes': 5, 'execution_context': {'environment': 'dev', 'database': 'boquim.tag.ong.br', 'original_source_name': '{SOURCE_NAME}', 'original_target_schema': '{TARGET_SCHEMA}', 'optional_filters': ['database_name'], 'filter_sources': {'database_name': 'databases_mysql.yml'}, 'description': 'Student evaluation fact table', 'created_at': '2025-09-29T14:28:38.077573', 'needs_source_resolution': True, 'needs_schema_resolution': True, 'is_fixed_schema': False, 'has_optional_filters': True}},
                    hotfix=hotfix_flag,
                    pool="mysql_prod_pool",
                    retries=1,
                    retry_delay=timedelta(minutes=5)
        )
    tg_1 >> tg_2 >> tg_3 >> tg_4 >> tg_5 >> tg_6 >> tg_7 >> tg_8 >> tg_9