"""
# AUTOGENERATED FILE - DO NOT EDIT MANUALLY
# Generated by DagGenerator on 2025-10-02T14:07:34.738461
# For environment: DEV
"""

from pendulum import datetime
from datetime import timedelta
from airflow.models.dag import DAG
from airflow.models.dagrun import DagRun
from airflow.utils.task_group import TaskGroup
from airflow.operators.python import PythonOperator

from utils.connections.connection_manager import DatabaseConnectionManager
from utils.connections.writer import CopyAndLoader
from plugins.operators.warehouse_etl_operator import WarehouseEtlOperator


def get_and_push_last_timestamp(
    ti, dag_run, target_table, target_schema_placeholder, timestamp_column, env
):
    """
    Queries the target table for the max timestamp and pushes it to XComs.
    This function is executed by the 'get_initial_timestamp' setup task.
    """
    hotfix_mode = (
        dag_run.conf.get("hotfix", False) if dag_run and dag_run.conf else False
    )

    print(
        f"Getting max timestamp for table '{{target_table}}'. Hotfix mode: {{hotfix_mode}}"
    )
    db_manager = DatabaseConnectionManager(environment=env, hotfix_mode=hotfix_mode)

    target_schema = (
        db_manager.sqlserver_config.schema
        if target_schema_placeholder == "{TARGET_SCHEMA}"
        else target_schema_placeholder
    )

    loader = CopyAndLoader(db_manager=db_manager)
    last_ts = loader._get_last_timestamp(target_table, timestamp_column, target_schema)

    if last_ts:
        print(f"Found last timestamp: {{last_ts}}")
    else:
        print("No last timestamp found. Assuming first execution.")

    ti.xcom_push(key="last_timestamp", value=last_ts)


with DAG(
    dag_id="workflow-warehouse__incremental_upsert__dev",
    start_date=datetime(2025, 1, 1),
    schedule="0 2 * * *",
    catchup=False,
    is_paused_upon_creation=True,
    tags=["warehouse", "autogenerated", "incremental_upsert", "dev"],
    doc_md="""Daily incremental_upsert at 2AM""",
) as dag:

    get_initial_timestamp = PythonOperator(
        task_id="get_initial_timestamp",
        python_callable=get_and_push_last_timestamp,
        op_kwargs={
            "target_table": "d_student",
            "target_schema_placeholder": "{TARGET_SCHEMA}",
            "timestamp_column": "inserted_at",
            "env": "dev",
        },
    )

    with TaskGroup(group_id="Batch_1_Stage_1") as tg_1:
        d_student__nossasenhoradagloria_tag_ong_br = WarehouseEtlOperator(
            task_id="d_student__nossasenhoradagloria_tag_ong_br",
            table_execution_dict={
                "table_name": "d_student",
                "stage": 1,
                "database": "nossasenhoradagloria.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/d_student.yml",
                "sql_path": "tables/d_student.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 48,
                    "batch_size": 5000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "nossasenhoradagloria.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student dimension table with personal information",
                    "created_at": "2025-10-02T14:07:34.738317",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
        d_student__buzios_tag_ong_br = WarehouseEtlOperator(
            task_id="d_student__buzios_tag_ong_br",
            table_execution_dict={
                "table_name": "d_student",
                "stage": 1,
                "database": "buzios.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/d_student.yml",
                "sql_path": "tables/d_student.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 48,
                    "batch_size": 5000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "buzios.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student dimension table with personal information",
                    "created_at": "2025-10-02T14:07:34.738328",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
        d_student__boquim_tag_ong_br = WarehouseEtlOperator(
            task_id="d_student__boquim_tag_ong_br",
            table_execution_dict={
                "table_name": "d_student",
                "stage": 1,
                "database": "boquim.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/d_student.yml",
                "sql_path": "tables/d_student.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 48,
                    "batch_size": 5000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "boquim.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student dimension table with personal information",
                    "created_at": "2025-10-02T14:07:34.738333",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
    with TaskGroup(group_id="Batch_2_Stage_1") as tg_2:
        d_student_discipline__nossasenhoradagloria_tag_ong_br = WarehouseEtlOperator(
            task_id="d_student_discipline__nossasenhoradagloria_tag_ong_br",
            table_execution_dict={
                "table_name": "d_student_discipline",
                "stage": 1,
                "database": "nossasenhoradagloria.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/d_student_discipline.yml",
                "sql_path": "tables/d_student_discipline.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 24,
                    "batch_size": 10000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "nossasenhoradagloria.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student discipline results dimension table",
                    "created_at": "2025-10-02T14:07:34.738338",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
        d_student_discipline__buzios_tag_ong_br = WarehouseEtlOperator(
            task_id="d_student_discipline__buzios_tag_ong_br",
            table_execution_dict={
                "table_name": "d_student_discipline",
                "stage": 1,
                "database": "buzios.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/d_student_discipline.yml",
                "sql_path": "tables/d_student_discipline.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 24,
                    "batch_size": 10000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "buzios.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student discipline results dimension table",
                    "created_at": "2025-10-02T14:07:34.738342",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
        d_student_discipline__boquim_tag_ong_br = WarehouseEtlOperator(
            task_id="d_student_discipline__boquim_tag_ong_br",
            table_execution_dict={
                "table_name": "d_student_discipline",
                "stage": 1,
                "database": "boquim.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/d_student_discipline.yml",
                "sql_path": "tables/d_student_discipline.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 24,
                    "batch_size": 10000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "boquim.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student discipline results dimension table",
                    "created_at": "2025-10-02T14:07:34.738360",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
    with TaskGroup(group_id="Batch_3_Stage_2") as tg_3:
        f_avaliation__nossasenhoradagloria_tag_ong_br = WarehouseEtlOperator(
            task_id="f_avaliation__nossasenhoradagloria_tag_ong_br",
            table_execution_dict={
                "table_name": "f_avaliation",
                "stage": 2,
                "database": "nossasenhoradagloria.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/f_avaliation.yml",
                "sql_path": "tables/f_avaliation.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 24,
                    "batch_size": 15000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "nossasenhoradagloria.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student evaluation fact table",
                    "created_at": "2025-10-02T14:07:34.738395",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
        f_avaliation__buzios_tag_ong_br = WarehouseEtlOperator(
            task_id="f_avaliation__buzios_tag_ong_br",
            table_execution_dict={
                "table_name": "f_avaliation",
                "stage": 2,
                "database": "buzios.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/f_avaliation.yml",
                "sql_path": "tables/f_avaliation.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 24,
                    "batch_size": 15000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "buzios.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student evaluation fact table",
                    "created_at": "2025-10-02T14:07:34.738401",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
        f_avaliation__boquim_tag_ong_br = WarehouseEtlOperator(
            task_id="f_avaliation__boquim_tag_ong_br",
            table_execution_dict={
                "table_name": "f_avaliation",
                "stage": 2,
                "database": "boquim.tag.ong.br",
                "source_name": "{SOURCE_NAME}",
                "target_schema": "{TARGET_SCHEMA}",
                "trigger": "incremental_upsert",
                "model": "tables/f_avaliation.yml",
                "sql_path": "tables/f_avaliation.sql",
                "incremental_config": {
                    "source_timestamp_columns": ["updated_at"],
                    "target_timestamp_column": "inserted_at",
                    "lookback_hours": 24,
                    "batch_size": 15000,
                    "full_refresh": False,
                },
                "upsert_config": {
                    "source_key_columns": ["HASH_ID"],
                    "target_key_columns": ["HASH_ID"],
                },
                "pool": "mysql_prod_pool",
                "retries": 1,
                "retry_delay_minutes": 5,
                "execution_context": {
                    "environment": "dev",
                    "database": "boquim.tag.ong.br",
                    "original_source_name": "{SOURCE_NAME}",
                    "original_target_schema": "{TARGET_SCHEMA}",
                    "optional_filters": ["database_name"],
                    "filter_sources": {"database_name": "databases_mysql.yml"},
                    "description": "Student evaluation fact table",
                    "created_at": "2025-10-02T14:07:34.738405",
                    "needs_source_resolution": True,
                    "needs_schema_resolution": True,
                    "is_fixed_schema": False,
                    "has_optional_filters": True,
                },
                "quality_check_pipeline": [],
                "quality_check_params": {},
            },
            pool="mysql_prod_pool",
            retries=1,
            retry_delay=timedelta(minutes=5),
        )
    get_initial_timestamp >> tg_1 >> tg_2 >> tg_3
