import pytest
from pathlib import Path

from utils.planner.dag_generator import DagGenerator
from utils.planner.execution_planner import TableExecution
from utils.planner.warehouse_basic_config import (
    WorkflowConfig,
    Stage,
    TableLoad,
    IncrementalConfig,
    UpsertConfig,
    TriggerConfig,
)


@pytest.fixture
def sample_execution_plan() -> list:
    """
    Creates a sample execution plan for DAG generation tests.
    Returns a list of batches, each containing TableExecution objects for different stages and databases.
    """
    inc_config = IncrementalConfig(
        source_timestamp_columns=["ts"], target_timestamp_column="ts"
    )
    ups_config = UpsertConfig(source_key_columns=["id"])

    load_A = TableLoad(
        table_name="table_A",
        model="m",
        stage=1,
        depends_on=[],
        trigger="daily",
        retries=3,
        pool="pool_A",
        retry_delay_minutes=10,
    )
    load_B = TableLoad(
        table_name="table_B",
        model="m",
        stage=2,
        depends_on=["table_A"],
        trigger="daily",
        retries=1,
        pool="default_pool",
        retry_delay_minutes=5,
    )

    exec_A1 = TableExecution(
        table_name="table_A",
        stage=1,
        database="db1",
        source_name="src",
        target_schema="tgt",
        trigger="daily",
        model="m",
        sql_path="/fake/A.sql",
        incremental_config=inc_config,
        upsert_config=ups_config,
        pool=load_A.pool,
        retries=load_A.retries,
        retry_delay_minutes=load_A.retry_delay_minutes,
    )
    exec_A2 = TableExecution(
        table_name="table_A",
        stage=1,
        database="db2",
        source_name="src",
        target_schema="tgt",
        trigger="daily",
        model="m",
        sql_path="/fake/A.sql",
        incremental_config=inc_config,
        upsert_config=ups_config,
        pool=load_A.pool,
        retries=load_A.retries,
        retry_delay_minutes=load_A.retry_delay_minutes,
    )
    exec_B1 = TableExecution(
        table_name="table_B",
        stage=2,
        database="db1",
        source_name="src",
        target_schema="tgt",
        trigger="daily",
        model="m",
        sql_path="/fake/B.sql",
        incremental_config=inc_config,
        upsert_config=ups_config,
        pool=load_B.pool,
        retries=load_B.retries,
        retry_delay_minutes=load_B.retry_delay_minutes,
    )
    return [[exec_A1, exec_A2], [exec_B1]]


@pytest.fixture
def sample_workflow_config() -> WorkflowConfig:
    """
    Creates a valid sample WorkflowConfig for DAG generation tests.
    """
    load1 = TableLoad(
        table_name="table_A", model="m", stage=1, depends_on=[], trigger="daily"
    )
    stage1 = Stage(stage=1, loads=[load1])

    return WorkflowConfig(
        workflow_name="My_Test_Workflow",
        max_parallel_tasks=4,
        triggers={
            "daily": TriggerConfig(
                name="daily", schedule_interval="@daily", description="Daily run"
            )
        },
        stages=[stage1],
    )


def test_dag_generator_creates_correct_file_and_content(
    tmp_path: Path, sample_execution_plan, sample_workflow_config
):
    """
    Tests the complete DAG generation flow.
    Verifies that the DAG file is created and its content matches the expected structure and parameters.

    Example:
        The generated file should exist at the expected path and contain:
            - dag_id="my_test_workflow__daily__dev"
            - tags=["warehouse", "autogenerated", "daily", "dev"]
            - schedule="@daily"
            - import of WarehouseEtlOperator
            - TaskGroup definitions for each batch/stage
            - task_id, retries, pool, retry_delay for each TableExecution
            - correct dependencies between TaskGroups
    """
    output_dir = tmp_path / "dags"
    generator = DagGenerator(output_path=str(output_dir))
    test_environment = "dev"

    generator.generate_dags(
        sample_execution_plan, sample_workflow_config, environment=test_environment
    )

    expected_file = output_dir / f"dag__my_test_workflow__daily__{test_environment}.py"
    assert expected_file.exists(), "DAG file was not created."

    generated_code = expected_file.read_text()
    assert f'dag_id="my_test_workflow__daily__{test_environment}"' in generated_code
    assert (
        f'tags=["warehouse", "autogenerated", "daily", "{test_environment}"]'
        in generated_code
    )
    assert 'schedule="@daily"' in generated_code
    assert (
        "from plugins.operators.warehouse_etl_operator import WarehouseEtlOperator"
        in generated_code
    )
    assert 'with TaskGroup(group_id="Batch_1_Stage_1") as tg_1:' in generated_code
    assert 'with TaskGroup(group_id="Batch_2_Stage_2") as tg_2:' in generated_code
    assert 'task_id="table_A__db1"' in generated_code
    assert "retries=3" in generated_code
    assert 'pool="pool_A"' in generated_code
    assert "retry_delay=timedelta(minutes=10)" in generated_code
    assert "tg_1 >> tg_2" in generated_code
