table_name: "accumulated_data"
description: "accumulated_data OBT used for BI, better perfomance this way"
source_name: "{SOURCE_NAME}"
target_schema: "dbo_tia"

incremental_config:
  source_timestamp_columns: ["updated_at"]
  target_timestamp_column: "inserted_at"
  lookback_hours: 24
  batch_size: 10000
  full_refresh: false

optional_filters:
  - database_name
filter_sources:
  database_name: databases_mysql.yml