SELECT
    itd.register_type,
    itd.school_inep_id_fk,
    itd.instructor_inep_id,
    itd.instructor_fk,
    itd.classroom_inep_id,
    itd.classroom_id_fk,
    itd.role,
    itd.contract_type,
    itd.discipline_1_fk,
    itd.discipline_2_fk,
    itd.discipline_3_fk,
    itd.discipline_4_fk,
    itd.discipline_5_fk,
    itd.discipline_6_fk,
    itd.discipline_7_fk,
    itd.discipline_8_fk,
    itd.discipline_9_fk,
    itd.discipline_10_fk,
    itd.discipline_11_fk,
    itd.discipline_12_fk,
    itd.discipline_13_fk,
    itd.discipline_14_fk,
    itd.discipline_15_fk,
    itd.id,
    itd.hash,
    itd.hash_instructor,
    itd.hash_classroom,
    itd.regent,
    itd.created_at,
    itd.updated_at,
    '{{ database_raw }}' AS database_name
FROM {{ database }}.instructor_teaching_data AS itd
WHERE itd.updated_at > '{{ safe_timestamp }}';
