"""
Generates dynamic Airflow DAG Python files from a structured execution plan.
"""

from pathlib import Path
from typing import Dict, List
from collections import defaultdict
from datetime import datetime

from utils.logs.logging_functions import get_logger
from utils.planner.execution_planner import TableExecution
from utils.planner.warehouse_basic_config import WorkflowConfig, TriggerConfig


class DagGenerator:
    """
    Generates dynamic Airflow DAG Python files based on a validated execution plan.

    This class reads a structured execution plan and a workflow configuration
    to produce one or more DAG files. Each file corresponds to a unique trigger
    (e.g., 'daily', 'weekly') and environment (e.g., 'dev', 'prod'). It contains
    the necessary Airflow code, including TaskGroups for sequential batch
    execution and instances of the custom WarehouseEtlOperator for each task.
    """

    def __init__(self, output_path: str):
        """
        Initializes the DagGenerator.

        Args:
            output_path (str): The directory path where the generated DAG files
                will be saved.
        """
        self.output_path = Path(output_path)
        self.logger = get_logger("dag_generator")
        self.output_path.mkdir(parents=True, exist_ok=True)

    def generate_dags(
        self,
        execution_plan: List[List[TableExecution]],
        workflow_config: WorkflowConfig,
        environment: str,
        is_paused: bool = False,
    ):
        """
        Main method to generate all DAG files for a specific environment.

        It groups executions by their trigger and then generates a separate,
        environment-specific DAG file for each trigger.

        Args:
            execution_plan (List[List[TableExecution]]): The structured, batched
                plan from the ExecutionPlanner.
            workflow_config (WorkflowConfig): The main workflow configuration,
                containing trigger details like schedule intervals.
            environment (str): The target environment (e.g., 'dev', 'prod').
            is_paused (bool): If True, the generated DAG will be paused upon
                creation in Airflow.
        """
        self.logger.info(
            f"Starting DAG generation for environment: {environment.upper()}"
        )
        grouped_executions = self._group_plan_by_trigger(execution_plan)

        for trigger_name, batches in grouped_executions.items():
            try:
                trigger_config = workflow_config.triggers.get(trigger_name)
                if not trigger_config:
                    self.logger.warning(
                        f"Trigger '{trigger_name}' found in plan but not in workflow "
                        f"triggers config. Skipping.",
                        {"trigger_name": trigger_name},
                    )
                    continue

                self.logger.info(
                    f"Generating DAG file for trigger: '{trigger_name}'..."
                )

                file_content = self._generate_dag_file_content(
                    trigger_name,
                    trigger_config,
                    batches,
                    workflow_config.workflow_name,
                    environment,
                    is_paused,
                )

                file_name = f"dag__{workflow_config.workflow_name.lower()}__{trigger_name}__{environment}.py"
                file_path = self.output_path / file_name

                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(file_content)

                self.logger.info(f"Successfully generated DAG file: {file_path}")

            except Exception as e:
                self.logger.error(
                    f"Failed to generate DAG for trigger '{trigger_name}'. Original error: {e}",
                    extra_data={"trigger_name": trigger_name},
                )
                raise

    def _group_plan_by_trigger(
        self, execution_plan: List[List[TableExecution]]
    ) -> Dict[str, List[List[TableExecution]]]:
        """Groups the execution plan's batches by their trigger."""
        grouped = defaultdict(list)
        for batch in execution_plan:
            if not batch:
                continue
            trigger = batch[0].trigger
            grouped[trigger].append(batch)
        return grouped

    def _generate_dag_file_content(
            self,
            trigger_name: str,
            trigger_config: TriggerConfig,
            batches: List[List[TableExecution]],
            workflow_name: str,
            environment: str,
            is_paused: bool,
        ) -> str:
        """Generates the full Python source code for a single DAG file."""
        dag_id = f"{workflow_name.lower()}__{trigger_name}__{environment}"

        header = f'''"""
# AUTOGENERATED FILE - DO NOT EDIT MANUALLY
# Generated by DagGenerator on {datetime.now().isoformat()}
# For environment: {environment.upper()}
"""
from pendulum import datetime
from datetime import timedelta
from airflow.models.dag import DAG
from airflow.models.dagrun import DagRun
from airflow.utils.task_group import TaskGroup
from airflow.operators.python import PythonOperator

from utils.connections.connection_manager import DatabaseConnectionManager
from utils.connections.writer import CopyAndLoader
from plugins.operators.warehouse_etl_operator import WarehouseEtlOperator

'''

        # --- CORREÇÃO AQUI ---
        # A assinatura da função agora inclui 'dag_run' como um parâmetro
        python_callable_str = '''
def get_and_push_last_timestamp(ti, dag_run, target_table, target_schema_placeholder, timestamp_column, env):
    """
    Queries the target table for the max timestamp and pushes it to XComs.
    This function is executed by the 'get_initial_timestamp' setup task.
    """
    hotfix_mode = dag_run.conf.get("hotfix", False) if dag_run and dag_run.conf else False
    
    print(f"Getting max timestamp for table '{{target_table}}'. Hotfix mode: {{hotfix_mode}}")
    db_manager = DatabaseConnectionManager(environment=env, hotfix_mode=hotfix_mode)

    target_schema = (
        db_manager.sqlserver_config.schema
        if target_schema_placeholder == "{TARGET_SCHEMA}"
        else target_schema_placeholder
    )

    loader = CopyAndLoader(db_manager=db_manager)
    last_ts = loader._get_last_timestamp(target_table, timestamp_column, target_schema)

    if last_ts:
        print(f"Found last timestamp: {{last_ts}}")
    else:
        print("No last timestamp found. Assuming first execution.")
    
    ti.xcom_push(key='last_timestamp', value=last_ts)

'''

        final_execution = batches[-1][-1]
        target_table_for_ts = final_execution.table_name
        target_schema_placeholder_for_ts = final_execution.target_schema
        timestamp_column_for_ts = final_execution.incremental_config.target_timestamp_column

        dag_definition = f'''
{python_callable_str}
with DAG(
    dag_id="{dag_id}",
    start_date=datetime(2025, 1, 1),
    schedule="{trigger_config.schedule_interval}",
    catchup=False,
    is_paused_upon_creation={is_paused},
    tags=["warehouse", "autogenerated", "{trigger_name}", "{environment}"],
    doc_md="""{trigger_config.description}"""
) as dag:

    get_initial_timestamp = PythonOperator(
        task_id="get_initial_timestamp",
        python_callable=get_and_push_last_timestamp,
        # O op_kwargs não precisa passar 'dag_run' ou 'ti', o Airflow injeta automaticamente
        op_kwargs={{
            "target_table": "{target_table_for_ts}",
            "target_schema_placeholder": "{target_schema_placeholder_for_ts}",
            "timestamp_column": "{timestamp_column_for_ts}",
            "env": "{environment}"
        }}
    )
'''
        
        # O resto do código que gera TaskGroups e dependências continua o mesmo...
        # ...
        task_groups_code = []
        task_group_vars = []

        for i, batch in enumerate(batches):
            stage_num = batch[0].stage
            tg_var = f"tg_{i + 1}"
            task_group_vars.append(tg_var)

            tg_header = f"""
    with TaskGroup(group_id="Batch_{i + 1}_Stage_{stage_num}") as {tg_var}:"""

            tasks_code = []
            for execution in batch:
                task_id = (
                    f"{execution.table_name}__{execution.database.replace('.', '_')}"
                )
                task_variable_name = task_id.replace('-', '_')

                task_code = f"""
        {task_variable_name} = WarehouseEtlOperator(
            task_id="{task_id}",
            table_execution_dict={repr(execution.to_dict())},
            pool="{execution.pool or 'default_pool'}",
            retries={execution.retries},
            retry_delay=timedelta(minutes={execution.retry_delay_minutes})
        )"""
                tasks_code.append(task_code)

            task_groups_code.append(tg_header + "".join(tasks_code))

        dependencies_code = ""
        if task_group_vars:
            dependency_chain = " >> ".join(task_group_vars)
            dependencies_code = f"\n    get_initial_timestamp >> {dependency_chain}"


        return header + dag_definition + "".join(task_groups_code) + dependencies_code