workflow_name: "Workflow-Warehouse"
max_parallel_tasks: 3
pool: "mysql_prod_pool"

triggers:
  incremental_upsert:
    schedule_interval: "0 2 * * *"
    description: "Daily incremental_upsert at 2AM"
    incremental_reference_table: "d_student" 


  incremental_base_tables:
    schedule_interval: "0 1 * * *"
    description: "Daily incremental_upsert at 3AM"
    incremental_reference_table: "class_faults" 

stages:
  - stage: 1
    loads:
      - table_name: "d_student"
        model: "tables/d_student.yml"
        depends_on: []
        trigger: "incremental_upsert"
        pool: "mysql_prod_pool"
        
      - table_name: "d_student_discipline" 
        model: "tables/d_student_discipline.yml"
        depends_on: []
        trigger: "incremental_upsert"
        pool: "mysql_prod_pool"

      - table_name: "class_faults" 
        model: "tables/class_faults.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "classroom" 
        model: "tables/classroom.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "edcenso_discipline" 
        model: "tables/edcenso_discipline.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "edcenso_stage_vs_modality" 
        model: "tables/edcenso_stage_vs_modality.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev
    
      - table_name: "instructor_teaching_data" 
        model: "tables/instructor_teaching_data.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "schedule" 
        model: "tables/schedule.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "school_identification" 
        model: "tables/school_identification.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "student_enrollment" 
        model: "tables/student_enrollment.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

      - table_name: "student_identification" 
        model: "tables/student_identification.yml"
        depends_on: []
        trigger: "incremental_base_tables"
        pool: "mysql_prod_pool"
        env_skip:
          - dev

  - stage: 2
    loads:
      - table_name: "f_avaliation"
        model: "tables/f_avaliation.yml"
        depends_on: ["d_student", "d_student_discipline"]
        trigger: "incremental_upsert"
        pool: "mysql_prod_pool"