workflow_name: "Workflow-Warehouse"
max_parallel_tasks: 3
pool: "mysql_prod_pool"

triggers:
  incremental_upsert:
    schedule_interval: "0 2 * * *"
    description: "Daily incremental_upsert at 2AM"
    incremental_reference_table: "d_student" 


  incremental_base_tables:
    schedule_interval: "0 3 * * *"
    description: "Daily incremental_upsert at 3AM"
    incremental_reference_table: "d_student" 

stages:
  - stage: 1
    loads:
      - table_name: "d_student"
        model: "tables/d_student.yml"
        depends_on: []
        trigger: "incremental_upsert"
        pool: "mysql_prod_pool"
        
      - table_name: "d_student_discipline" 
        model: "tables/d_student_discipline.yml"
        depends_on: []
        trigger: "incremental_upsert"
        pool: "mysql_prod_pool"

  - stage: 2
    loads:
      - table_name: "f_avaliation"
        model: "tables/f_avaliation.yml"
        depends_on: ["d_student", "d_student_discipline"]
        trigger: "incremental_upsert"
        pool: "mysql_prod_pool"